apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: megamessengerdev/auth
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: megamessengerdev
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: NODE_ENV
              value: 'development'
            - name: COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: cookie-key
                  key: COOKIE_KEY
            - name: COOKIE_SESSION_NAME
              valueFrom:
                secretKeyRef:
                  name: cookie-session-name
                  key: COOKIE_SESSION_NAME
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-client-secret
                  key: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-client-id
                  key: GOOGLE_CLIENT_ID
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
